### ISSUE TITLE
sWGA and PCR QC numbers pulled into metadata file

### ISSUE THREAD

**Issue by JasonAHendry** [nomads-community/warehouse#9]
It would be great if based on the sWGA and PCR identifiers, `warehouse` pulled the PCR and sWGA numbers into the final sample metadata. These numbers are some of the most important for diagnosing a samples performance and at present they need to be extracted manually from separate excel spreadsheets.

I am not sure of the process of going from XLSX to CSV, but if:
1. The completed experiment templates were stored as CSV, or we could get python to load multi-sheet XLSX
2. The files had a reasonably consistent name
3. The identifiers were unique

We should be able to search directory for the critical file(s) which contain sWGA/PCR QC numbers covering the library, concatenated them (vertical append), then left merge on the library table to bring these numbers in.

I could help code this as well, once we have some example data inside of the repo to work from.

Thank you, Jason

**Comment by danieljbridges** [comment]
The latest version address all of the above requirements. Please test and let me know if it isn't what you envisioned....

**Comment by danieljbridges** [comment]
Warehouse now imports all experimental data from all samples in a sequencing run to ensure that swga and pcr metrics are included in the seqfolders sample_info.csv file
